### PR TITLE
feat(meta): Orgs-features sidebar meta component

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by aredridel** [comment]
screen shot 2016-05-09 at 15 17 45

**Comment by stubbornella** [comment]
👀

**Comment by aredridel** [comment]
Sorry for the SVG spam there!

I want to get handlebars rendering in the style guide at some point so I can show off the much more trivial handlebars invocation for examples.

**Comment by stubbornella** [comment]
looks good to me! That design is so clean I thought you'd screen grabbed the mockup. Nice work!

**Pull request merged**
