### PR TITLE
Mobile nav finder fix

### PR DESCRIPTION
**Pull request by jefflembeck**
fix(lists): mobile view

This provides a nice mobile view for nav-finder.

### CODE REVIEW

**Comment by aredridel** [comment]
wow. Really don't love the magic. Is it content dependent?

**Comment by jefflembeck** [comment]
Unfortunately, yes. We can, however- work an ellipsis in there and Max-width things so we can have the numbers be less magical and more on point with BPs

**Comment by aredridel** [comment]
That, that sounds excellent.

**Comment by aredridel** [comment]
Gosh this looks good.

**Pull request merged**
