### PR TITLE
chore(PUI): document events and how we use them

### PR DESCRIPTION
**Pull request by jefflembeck**
We use a document message bus system for handling front end events, here
is some quick documentation on how to use it.

### CODE REVIEW

**Comment by aredridel** [comment]
I was going to say similarly: Should events be named after the methods that trigger them? Or the thing that happened? Before or after it happens? In the same event loop?

**Comment by jefflembeck** [comment]
> why does the ":bomb:::fire:" event happen inside :bomb:.:fire:?

Because this event should trigger every time :bomb:.:fire: is called, so calling it within the method insures that.

> Should events be named after the methods that trigger them? Or the thing that happened?

I think the thing that happened (in case there is a toggle method, or something to that effect). I could probably lay this out better.

>  I would expect that if I trigger :bomb:::fire:, then :bomb:.:fire: would be called, not the other way around?
> Before or after it happens?

Ooo.. now we're talking - ok, I _definitely_ think _after_. But, I am really into also triggering an event before along the lines of :bomb:.:fire:`:before` at the beginning of the thing happening.

This is great during menus opening and closing, anything with a transition, etc.

**Comment by aredridel** [comment]
Yeah, after makes sense in general, to me too, and in the same tick if possible.

Does it need to be 1:1 mapping of method name to event name? Should they always be the same?

**Comment by jefflembeck** [comment]
> Does it need to be 1:1 mapping of method name to event name? Should they always be the same?

I say no, but method names should be pretty damn descriptive of what's happening, so it's likely this will happen from time to time.

That being said, as mentioned above, a method like `toggle` will likely trigger `opened` or `closed` and `open` might trigger `opened` (same with `close`)

**Comment by aredridel** [comment]
That makes tons of sense -- since events tend to be past-tense verbs, and methods present-tense ones, naive cases will have a pretty direct mapping.

**Comment by jefflembeck** [comment]
I'll update the docs to reflect that.

**Pull request merged**
