### PR TITLE
feat(backgrounds): support for contained backgrounds

### PR DESCRIPTION
**Pull request by aredridel**
This allows us to position images as background decoration, potentially
over color or gradient backgrounds by combining linear gradient and
image backgrounds.

### CODE REVIEW

**Comment by aredridel** [comment]
Request for comments: should I add classes that map to the 8 directions for images? like `.bg-contained-bottom-right`, to put the image in a particular place, rather than inlining that?

**Comment by aredridel** [comment]
Or maybe orthogonal direction classes: `bg-contain bg-bottom-right`

**Comment by jefflembeck** [comment]
orthoganal direction classes certainly feel more _right_ to me, but I'm not sure the conventions wrt bootstrap

**Comment by aredridel** [comment]
Hmm. Alright. Easy enough to generate those.

**Comment by aredridel** [comment]
screen shot 2016-03-10 at 16 42 41

**Comment by jefflembeck** [comment]
:sheep:

**Pull request merged**
