### PR TITLE
Marginalia

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by aredridel** [comment]
screen shot 2016-04-19 at 19 05 05

**Comment by aredridel** [comment]
Yes I can! It should match the padding and I should document that :P

**Comment by jefflembeck** [comment]
So, this spaces things out to the left super well, but how do we handle placement on the vertical line as well? Is that within the scope of this component?

**Comment by aredridel** [comment]
screen shot 2016-04-20 at 09 03 56

**Pull request merged**
