### PR TITLE
feat(panels): A basic info panel

### PR DESCRIPTION
**Pull request by aredridel**
[#119240869]

### CODE REVIEW

**Comment by aredridel** [comment]
screen shot 2016-07-15 at 12 24 45

**Comment by jefflembeck** [comment]
@aredridel these look great, where are we using them?

**Comment by aredridel** [comment]
top of the 'add members' page, saying "wombatinabox.gif Add members for $7/month each!"

**Comment by jefflembeck** [comment]
Awesome! These match perfectly. Last Q: any reason this can't be accomplished with alerts?

**Comment by aredridel** [comment]
Border color.

**Comment by aredridel** [comment]
(panel for shape + round corners, alert for background color... meh. I had it mostly working but this is way cleaner and context-free.)

**Comment by jefflembeck** [comment]
Good enough reasoning for me. 🐑

**Pull request merged**
