### PR TITLE
Give SVG-containing cells explicit heights so they don't default to 150px in ie

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by aredridel** [comment]
screen shot 2016-10-11 at 14 59 47
screen shot 2016-10-11 at 15 04 53

**Comment by jefflembeck** [comment]
omg. what?

**Review by jefflembeck — APPROVED** [review]
LGTM. Explicit heights are A+

**Comment by aredridel** [comment]
https://github.com/npm/www/issues/36 Yeah, this. 😱

**Pull request merged**
