### PR TITLE
feat(utils): screen-filling utility

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by aredridel** [comment]
screen shot 2016-10-19 at 15 19 12

**Comment by aredridel** [comment]
in situ, works like so:

screen shot 2016-10-19 at 15 19 05
screen shot 2016-10-19 at 15 18 55
screen shot 2016-10-19 at 13 21 20

**Comment by aredridel** [comment]
Tested in IE; works well there. Tested in IE and Chrome and FF, no bugs there. (:confetti_ball:)

**Comment by aredridel** [comment]
At mobile sizes, basically has no effect: our footer is always more than a page tall at those sizes.

**Comment by aredridel** [comment]
Reasoning for this change is https://github.com/npm/npm-website/issues/676, particularly point 9.

**Review by jefflembeck — APPROVED** [review]
LGTM

**Pull request merged**
