### PR TITLE
feat(forms): An Org Scope Input

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by aredridel** [comment]
screen shot 2016-05-11 at 11 44 38

**Comment by aredridel** [comment]
@stubbornella @rockbot thoughts?

**Comment by stubbornella** [comment]
I wonder if the "@" symbol would be read by screen readers as CSS content?

**Comment by stubbornella** [comment]
Otherwise, looks good.

**Comment by aredridel** [comment]
VoiceOver doesn't read it, but I explicitly put a `speak: none` in there as well.

**Pull request merged**
