### PR TITLE
Remove instance-scales component

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by stubbornella** [comment]
We were going to hold off on deleting components until after we delivered the on-site flow. While this is an obvious component that we won't need, I'd rather be methodical about removing unused stuff when we are relaxed and not under time crunch. It's just not the most important thing we can be doing right now.

**Comment by stubbornella** [comment]
There are vars associated with the instance scale component that would also need to be removed (of course making sure they aren't used elsewhere).

in pui-variables.scss

```
// Instance Scale SVG
// -------------------------
$instance-scale-gradient-start: $neutral-9;
$instance-scale-gradient-end:   rgba(255,255,255,0);
```

**Comment by aredridel** [comment]
Oh excellent! 

Learning is part of why I went ahead and did it. Nice to understand how all the pieces fit together.

What was the reason for centralizing variables instead of leaving them in the component?

**Comment by aredridel** [comment]
Close in favor of #23

**Comment by stubbornella** [comment]
@aredridel bootstrap centralizes the vars, so it was a decision that was made by the underlying framework. That said, it turned out to work quite well because designers often felt comfy editing the variables folder in ways they didn't in the full on sass. It made collaboration work well.

It was necessary from bootstraps perspective because you don't want to edit the component files or you end up in upgrade _hell_. :)

**Comment by aredridel** [comment]
Makes sense!

**Pull request closed without merging**
