### PR TITLE
feat(background): add .bg-stretched for full-bleed backgrounds ignoring intrinsic aspect ratio

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by stubbornella** [comment]
What story this is part of?

**Comment by stubbornella** [comment]
Oh, and can you upload a screenshot of what you were going for and where it ended up?

**Comment by aredridel** [comment]
I can, but I realized I want to try a different approach that will be simpler and makes this class not needed

**Comment by aredridel** [comment]
This is a part of the homepage hero story

**Pull request closed without merging**
